### ISSUE TITLE
Using the flot.time plugin

### ISSUE THREAD

**Issue by Badestrand** [rodrigowirth/react-flot#1]
Thank you very much for this repository!

I can't get it working with the time plugin, the error "Time mode requires the flot.time plugin" appears. Is this a matter of webpack configuration or do I have to 'require' the plugin somehow?

**Comment by Badestrand** [comment]
Alright, I solved it with
```
require('../node_modules/react-flot/flot/jquery.flot.time.min')
```
in one of my source files!

**Comment by Badestrand** [comment]
Maybe you could add to the README how to include the flot plugins this way

**Comment by rodrigowirth** [comment]
Thank you @Badestrand, I'm going to update the readme file.
