### ISSUE TITLE
missing jQuery (issue with jquery.flot.js?)

### ISSUE THREAD

**Issue by mads79** [rodrigowirth/react-flot#3]
Tried a really simple example:

```
import React, { Component } from 'react';
import './App.css';
import ReactFlot from 'react-flot'

var data = [[0, 3], [4, 8], [8, 5], [9, 13]];
var options = {};

class App extends Component {
  render() {
    return (
      <div className="App">
	    <ReactFlot data={data} options={options} />
      </div>
    );
  }
}

export default App;

```
fails with the following error in chrome.

```
jquery.flot.min.js:7 Uncaught ReferenceError: jQuery is not defined
    at Object.<anonymous> (jquery.flot.min.js:7)
    at __webpack_require__ (bootstrap e55281c…:555)
    at fn (bootstrap e55281c…:86)
    at Object.<anonymous> (ReactFlot.js:25)
    at __webpack_require__ (bootstrap e55281c…:555)
    at fn (bootstrap e55281c…:86)
    at Object.<anonymous> (index.js:1)
    at __webpack_require__ (bootstrap e55281c…:555)
    at fn (bootstrap e55281c…:86)
    at Object.<anonymous> (App.js:3)
```

any suggestions on how to get around that? 

**UPDATE:**
A workaround for me is to import jQuery and jquery.flot.js globally on the script document, and then refer to window.$ instead of $ in ReactFlot.jsx. For some reason the jQuery object that's imported in ReactFlot.js isn't available inside jquery.flot.min.js. I have a feeling I'm missing something obvious here :smile:  I'm adding the <ReactFlot> component to the setup I get from create-react-app BTW.

**Comment by rodrigowirth** [comment]
Hi @mads79, are you using webpack?

**Comment by rodrigowirth** [comment]
Hi @mads79, in order to avoid adding a fixed version of jQuery to the project, I have added a warning to let the people know that jQuery should be available. Please have a look at the README.md file. 

Thanks for helping,
