### ISSUE TITLE
add typescript data

### ISSUE THREAD

**Issue by romor** [rodrigowirth/react-flot#5]
Do you plan to bundle TypeScript type information into this package?
This would be very useful to me.

**Comment by rodrigowirth** [comment]
Hi @brunolm, would like to help us with that? :grinning:

**Comment by rodrigowirth** [comment]
Hi @romor,

I have added the type script information.

https://github.com/rodrigowirth/react-flot/blob/master/src/ReactFlot.d.ts

Tell me if you need any help.

Cheers,
